### PR TITLE
doc: params missing

### PR DESCRIPTION
**Pull request by EricPoker**

### CODE REVIEW

**Comment by santigimeno** [comment]
First of all, thanks for the PR.
WRT the proposed change, what was the reason for making this modification? `42 * * * *` is as perfectly valid as `42 * * * * *`

**Comment by EricPoker** [comment]
Because it doesn't work for me when use `42 * * * *` on node 6.9.1.

**Comment by rtodea** [comment]
Hi @EricPoker,

Are you sure it does not work?

Please keep in mind that `42 * * * *` means that the job will be triggered when the **minute** is 42 (e.g. 19:42, 20:42, etc.).
In the second variant, `42 * * * * *`, the job will be triggered when the **second** is 42 (e.g. 19:00:42, 19:01:42, ...) and might be quickly visible.

Also, I tested the `6.9.1` and everything works as expected.

**Comment by EricPoker** [comment]
Sorry, it's my misunderstanding.I thought `42 * * * *` means that the job will be triggered when the second is 42.If the doc add some comments for this example result, will better.

**Comment by santigimeno** [comment]
> If the doc add some comments for this example result, will better.

@EricPoker I think it's a good idea. If you create a PR with that info, I'll gladly merge it. Thanks!

**Comment by EricPoker** [comment]
LGTM.Have done! :)

**Comment by santigimeno** [comment]
Landed in https://github.com/node-schedule/node-schedule/commit/93a174cb15e48d5d6ff319ed584d44aae39c3230. Thanks!

**Pull request closed without merging**
