### PR TITLE
Error w/ changing system time

### PR DESCRIPTION
**Pull request by ytkang**
bug fix about issue #214

### CODE REVIEW

**Comment by santigimeno** [comment]
@ytkang thanks for doing this :) . I didn't have the time. Could you add some test to make sure the issue is fixed after applying your changes?

**Comment by ytkang** [comment]
@santigimeno. I tried to make test case with this codes

     "Run job with future time": function(test) {
      test.expect(2);
      var DAY1 = 24 * 60 * 60 * 1000;
      var timeout = 10000;
      var tomorrow = new Date(clock.now + DAY1);
      var job = schedule.scheduleJob('0 * * * * *', function() {
        test.ok(true);
      });

      var job2 = schedule.scheduleJob(tomorrow, function(){
        test.ok(true);
        console.log("this called only after test.done()");
      });


      clock.setSystemTime(tomorrow);
      clock.tick(timeout);

      setTimeout(function () {
        job.cancel();
        job2.cancel();
        test.done();
        console.log('done');
      }, 20000);
      clock.tick(20000);
    } 

But the job2's callback is called only after test.done(). very weird.
(I tested this using master branch not my codes.)

Result of previous codes (current master)

    done
    this called only after test.done()
    this called only after test.done()
    ✖ .scheduleJob(cron_expr, fn) - Run job with future time.

Currently, I couldn't find how to make proper test case. 
Hum.. Actually This issue is only happened when we are changing machine's time(for testing), so I don't think it is critical issue;
If you want you can discard this :)

**Comment by santigimeno** [comment]
@tejasmanohar thoughts? I'm not too sure about this. I think the right solution would be to remove the `one-shot jobs` from the pendingInvocations once they're fired.

**Comment by tejasmanohar** [comment]
I agree w/ you, @santigimeno.

**Comment by kibertoad** [comment]
@ytkang Would you consider finishing this PR?

**Comment by ytkang** [comment]
@kibertoad sorry I can't follow this issue now.

**Pull request closed without merging**
