### PR TITLE
src: fix scheduling with RR with year property set

### PR DESCRIPTION
**Pull request by santigimeno**
Avoid an infinite loop by checking if we're past the year set in the
RecurrenceRule.

### CODE REVIEW

**Comment by santigimeno** [comment]
I'll add tests in the following days

**Comment by santigimeno** [comment]
PR ready. @albertdatui can you PTAL? Thanks!

**Comment by santigimeno** [comment]
@albertdatui ping :)

**Comment by albertdatui** [comment]
@santigimeno, apologize for the delayed response.

everything LGTM, well done! :)

**Comment by santigimeno** [comment]
Landed in https://github.com/node-schedule/node-schedule/commit/0883f24dcb2717f04aba9bb8503f260c706ae144. Thanks!

**Comment by santigimeno** [comment]
> small note here, we used to allow the execution of job if it is scheduled in the past but now, the feature is disabled. However, if we want to enable this functionality again, we need to modify this code. CMIIW

@albertdatui not too sure as the check is done IIRC in the `schedule` method: https://github.com/node-schedule/node-schedule/blob/master/lib/schedule.js#L203

**Comment by santigimeno** [comment]
Published in `1.1.1`

**Pull request merged**
