### PR TITLE
Fix the bug that canceled job still keeps running

### PR DESCRIPTION
**Pull request by wux5**
Fixes https://github.com/node-schedule/node-schedule/issues/369

### CODE REVIEW

**Comment by wux5** [comment]
If you want to test the fix, you can easily reproduce the issue with this code, and verify it works with the new version.

    var nscheduler = require('node-schedule');

    var schedName = 'test-sched';
    var job = nscheduler.scheduleJob(schedName, '*/1 * * * * *', function () {
      var time1 = Date.now();
      console.log(time1, schedName + ' ran successfully');
      while (Date.now() - time1 < 2000) {
        // 
      }
    });

    setTimeout(function () {
      job.cancel();
    }, 2100);

Or you can also test it with @nnoto 's more complex test case in https://github.com/node-schedule/node-schedule/issues/369

**Comment by rostislavprovodenko** [comment]
When is it planned to be merged?

**Comment by santigimeno** [comment]
When time permits :)

**Comment by santigimeno** [comment]
Landed in https://github.com/node-schedule/node-schedule/commit/9f68aa031c07797295fdc17418410552925f0d97 with a test added in https://github.com/node-schedule/node-schedule/commit/f9cc2c815b8af1512e359fb12ac3f2976de0edac. Thanks a lot @wux5 !

**Comment by santigimeno** [comment]
Published in `1.2.5`

**Comment by nirajtathe** [comment]
I am also facing the same issue. I have created 2 jobs with different names and execution time. But it is only executing the second job at 1st job execution time and 2nd as well. I have also downloaded 1.2.0 version but still facing the same problem. I have saved the job object and printed, it is showing correct job name (job name which I had assigned). I am unable to find any solution and move ahead.

**Comment by santigimeno** [comment]
Sure. Can you open a new issue explaining the problem with code that reproduces it?

**Comment by nirajtathe** [comment]
@santigimeno I have created new issue #398

**Pull request closed without merging**
