### PR TITLE
Linting + Fixing a performance issue

### PR DESCRIPTION
**Pull request by rodrigoalviani**

### CODE REVIEW

**Comment by rodrigoalviani** [comment]
Linting + fix performance issue

**Comment by santigimeno** [comment]
:+1:  on removing the deletes and removing commented code.
Not too sure about removing the braces though. @tejasmanohar what's your take?

**Comment by rodrigoalviani** [comment]
The 'delete' remaps an entire object. This is 99x slower than a simple var = null

**Comment by santigimeno** [comment]
Yes, I understand.
What I was questioning was the removing of braces in on-liner `if else`

**Comment by tejasmanohar** [comment]
@rodrigoalviani @santigimeno I'd prefer to leave the braces in to keep everything consistent and adhere to current style of the code.

https://github.com/airbnb/javascript#blocks

**Comment by rodrigoalviani** [comment]
@tejasmanohar Look at #b948e14

**Comment by tejasmanohar** [comment]
You got it!

**Pull request merged**
