### PR TITLE
Bug fix#225 and #229, updating cron-parser

### PR DESCRIPTION
**Pull request by albertdatui**
The updated package removes the convenience method in the date, instead there is new class of Date object. That is why, I am adding back increment.js.

For the test file, I don't know why it failed the testcase when timeout = 3000. I suspect that there might be a delay when dispatching the job.

Thanks to @Xorcerer

### CODE REVIEW

**Comment by santigimeno** [comment]
@albertdatui Thanks for this! Can you rework the PR against `master` instead of `dev`? Thanks!

**Comment by santigimeno** [comment]
Also, see https://github.com/node-schedule/node-schedule/pull/230#issuecomment-173866282

**Comment by tejasmanohar** [comment]
@albertdatui If you can rework this PR for `master` instead of `dev`, we can merge it. `dev `'s really behind, and i think it'd be a good idea to push a new version of node-schedule up to npm w/ this fix before worrying about other enhancements

**Comment by tejasmanohar** [comment]
seems we have https://github.com/node-schedule/node-schedule/pull/231 instead now? @santigimeno @albertdatui

**Pull request closed without merging**
