### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jonhester**
Updates `long-timeout` to current version. I also `sinon` to the current version and prefix all the devDependencies with `^`. I think we should keep the dependencies locked to avoid potential issues in new patch or minor releases that we haven't tested with.

### CODE REVIEW

**Comment by santigimeno** [comment]
LGTM

**Comment by tejasmanohar** [comment]
You can use branches on node-schedule rather than forks to PR now that you're a collaborator, too. btw

**Comment by jonhester** [comment]
@tejasmanohar Cool, what would your preference be one branch per feature/fix. Or stay with pull requests? I'm fine with whatever you prefer.

**Comment by jonhester** [comment]
@tejasmanohar The only thing that may be better about pull requests is that they are easier to merge based on tests/linting passing since that won't work the same way with commits to other branches.

**Comment by tejasmanohar** [comment]
Oh, I meant you can send PRs from branches on node-schedule/node-schedule rather than a fork.

**Comment by tejasmanohar** [comment]
In general, PRs are best except for small changes / fixes that are really indisputable. For ongoing work, use a non-master branch, for sure.

**Comment by jonhester** [comment]
Ahh, that makes way more sense. I've just recently started contributing so I'm new to this.

**Pull request merged**
