### PR TITLE
Feature reschedule

### PR DESCRIPTION
**Pull request by albertdatui**
@santigimeno reschedule feature

- it supports rescheduling from/to any spec type
- new private variable to count number of triggered job
- it can reschedule a job that has been executed

### CODE REVIEW

**Comment by santigimeno** [comment]
@albertdatui This looks fantastic. Thanks!

**Comment by santigimeno** [comment]
Merged in 7211a7e2de5db1fd31bd0622f5c997e7e5a2391f and 817406af831b8528658638b6e887e80928ed5d7a

**Comment by santigimeno** [comment]
We should bump a minor version for this change. We'll wait for https://github.com/node-schedule/node-schedule/pull/235 to release `1.1.0`

**Comment by tejasmanohar** [comment]
:D

**Comment by santigimeno** [comment]
@albertdatui Thanks for your contributions. Would you like to be added as a collaborator for the project? It would be great.
/cc @tejasmanohar

**Comment by tejasmanohar** [comment]
+1, @santigimeno - i think you're an org owner so you should be able to add him as a collab [here](https://github.com/orgs/node-schedule/invitations/new)

**Comment by santigimeno** [comment]
Ok. Thanks for the heads up :)

**Comment by albertdatui** [comment]
@santigimeno @tejasmanohar

I will be very humbled to be added as project collaborator.

Looking forward to be part of the project

**Comment by santigimeno** [comment]
@albertdatui that's great :). Invitation sent and welcome aboard.

**Comment by santigimeno** [comment]
@tejasmanohar I think he should also be added to `npm` so he can publish new versions, right?

**Comment by tejasmanohar** [comment]
@santigimeno sure! see if https://docs.npmjs.com/cli/owner works from your npm account. if not, i'll do it. npm doesn't have too much of a fine-grained permissions structure like github

**Comment by santigimeno** [comment]
Released in `1.1.0`

**Pull request merged**
