### PR TITLE
Fixed scheduleJob not working on leap year. #229

### PR DESCRIPTION
**Pull request by Xorcerer**
Updated the dependency, cron-parser, to 1.1.0.
https://github.com/node-schedule/node-schedule/issues/229

### CODE REVIEW

**Comment by Xorcerer** [comment]
Why do updating the cron-parser fail the CI process?
Checking it.

**Comment by Xorcerer** [comment]
The CI failed before this pull request, so, it is another story.

**Comment by albertdatui** [comment]
Hi,

you can look at my pull request #193 where I changed some of the test file. Hopefully, by doing that, CI will pass your pull request.

Thanks

**Comment by santigimeno** [comment]
@Xorcerer Thanks for the PR. I've tried upgrading the cron-parser package and got the same failures as in travis. One of them is fixed by applying the fix from @albertdatui  in https://github.com/node-schedule/node-schedule/pull/231 but there are still more failures. Do you plan trying to fix those?

**Comment by Xorcerer** [comment]
Sure,  my pleasure.
I don't know what is a better process, maybe, let me start fixing it after
you approve both PRs. So I could got the right code base to work with.

2016年1月22日星期五，Santiago Gimeno <notifications@github.com> 写道：

> @Xorcerer <https://github.com/Xorcerer> Thanks for the PR. I've tried
> upgrading the cron-parser package and got the same failures as in travis.
> One of them is fixed by applying the fix from @albertdatui
> <https://github.com/albertdatui> in #231
> <https://github.com/node-schedule/node-schedule/pull/231> but there are
> still more failures. Do you plan trying to fix those?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-schedule/node-schedule/pull/230#issuecomment-173866282>
> .
>


-- 

----
Cellphone: +86 137 6413 1714
twitter: @Xorcerer
github: https://github.com/Xorcerer
Gtalk: xorcererzc@gmail.com

**Comment by santigimeno** [comment]
They are independent. I think you could do it right away.

And thanks!

**Comment by santigimeno** [comment]
FYI: with cron-parser@0.7.0 the failing tests pass. With the next version cron-parser@1.0.0 they don't.

**Comment by Xorcerer** [comment]
Thank you. I are about to start it in 2 hours.

2016年1月22日星期五，Santiago Gimeno <notifications@github.com> 写道：

> FYI: with cron-parser@0.7.0 the failing tests pass. With the next version
> cron-parser@1.0.0 they don't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-schedule/node-schedule/pull/230#issuecomment-173870079>
> .
>


-- 

----
Cellphone: +86 137 6413 1714
twitter: @Xorcerer
github: https://github.com/Xorcerer
Gtalk: xorcererzc@gmail.com

**Comment by tejasmanohar** [comment]
#233 seems to work

**Pull request closed without merging**
