### PR TITLE
WIP: Timezone support

### PR DESCRIPTION
**Pull request by santigimeno**
Mostly working. I think we still have a bug when DST ends. Looking into it

### CODE REVIEW

**Comment by tejasmanohar** [comment]
tests need to be updated

https://travis-ci.org/node-schedule/node-schedule/jobs/59886495

**Comment by santigimeno** [comment]
The tests pass now. 2 caveats:
- Still have to test / fix DST end transitions.
- Using node-time makes the module not compatible with Windows.

**Comment by santigimeno** [comment]
I think that before merging this, some discussion is required:
- What do you think of the API? I could not come up with something better but not too sure is good enough.
- Is acceptable removing Windows support? Maybe there's a pure-js module out there that gives us the same functionality.
- From the tests I've been performing, DST end transitions are not handled correctly when using `RecurrenceRule`'s. Probably not an issue with this PR but we should be fixing it before making a new release.
- We need more tests of this functionality: not only with `RecurrenceRule`'s but with cron expressions, dates, strings, etc. I'll do this.

@tejasmanohar @jonhester Thoughts?

**Comment by JibstaMan** [comment]
How about using [timezone](https://github.com/bigeasy/timezone)? I've just started using it (in development) and it supports Windows. I think not supporting Windows would be a shame, since node-schedule is very useful even without timezone support.

Some good [documentation](http://bigeasy.github.io/timezone/). Hope this helps!

**Comment by santigimeno** [comment]
@JibstaMan Thanks for the heads up! I'll take a look at it

**Pull request merged**
